
package cn.com.zysoft;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CallInterfaceFault", targetNamespace = "http://www.zysoft.com.cn/")
public class CallInterfaceFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CallInterfaceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CallInterfaceFault_Exception(String message, CallInterfaceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CallInterfaceFault_Exception(String message, CallInterfaceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cn.com.zysoft.CallInterfaceFault
     */
    public CallInterfaceFault getFaultInfo() {
        return faultInfo;
    }

}
