
package cn.com.zysoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HisEntranceWsPortType", targetNamespace = "http://www.zysoft.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HisEntranceWsPortType {


    /**
     * 
     * @param msgHeader
     * @param msgBody
     * @return
     *     returns java.lang.String
     * @throws CallInterfaceFault_Exception
     */
    @WebMethod(operationName = "CallInterface", action = "http://www.zysoft.com.cn/CallInterface")
    @WebResult(name = "payload", targetNamespace = "http://www.zysoft.com.cn/")
    @RequestWrapper(localName = "CallInterface", targetNamespace = "http://www.zysoft.com.cn/", className = "cn.com.zysoft.CallInterface")
    @ResponseWrapper(localName = "CallInterfaceResponse", targetNamespace = "http://www.zysoft.com.cn/", className = "cn.com.zysoft.CallInterfaceResponse")
    public String callInterface(
        @WebParam(name = "msgHeader", targetNamespace = "http://www.zysoft.com.cn/")
        String msgHeader,
        @WebParam(name = "msgBody", targetNamespace = "http://www.zysoft.com.cn/")
        String msgBody)
        throws CallInterfaceFault_Exception
    ;

}
