
package cn.com.zysoft;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HisEntranceWs", targetNamespace = "http://www.zysoft.com.cn/", wsdlLocation = "file:/E:/tool/JDK/Java8/jdk/bin/lzry.wsdl")
public class HisEntranceWs
    extends Service
{

    private final static URL HISENTRANCEWS_WSDL_LOCATION;
    private final static WebServiceException HISENTRANCEWS_EXCEPTION;
    private final static QName HISENTRANCEWS_QNAME = new QName("http://www.zysoft.com.cn/", "HisEntranceWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/tool/JDK/Java8/jdk/bin/lzry.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISENTRANCEWS_WSDL_LOCATION = url;
        HISENTRANCEWS_EXCEPTION = e;
    }

    public HisEntranceWs() {
        super(__getWsdlLocation(), HISENTRANCEWS_QNAME);
    }

    public HisEntranceWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISENTRANCEWS_QNAME, features);
    }

    public HisEntranceWs(URL wsdlLocation) {
        super(wsdlLocation, HISENTRANCEWS_QNAME);
    }

    public HisEntranceWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISENTRANCEWS_QNAME, features);
    }

    public HisEntranceWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HisEntranceWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HisEntranceWsPortType
     */
    @WebEndpoint(name = "HisEntranceWsHttpSoap11Endpoint")
    public HisEntranceWsPortType getHisEntranceWsHttpSoap11Endpoint() {
        return super.getPort(new QName("http://www.zysoft.com.cn/", "HisEntranceWsHttpSoap11Endpoint"), HisEntranceWsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HisEntranceWsPortType
     */
    @WebEndpoint(name = "HisEntranceWsHttpSoap11Endpoint")
    public HisEntranceWsPortType getHisEntranceWsHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.zysoft.com.cn/", "HisEntranceWsHttpSoap11Endpoint"), HisEntranceWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISENTRANCEWS_EXCEPTION!= null) {
            throw HISENTRANCEWS_EXCEPTION;
        }
        return HISENTRANCEWS_WSDL_LOCATION;
    }

}
